name: CI-CD to k8s via Tailscale
on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Connect to Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci          # almeno un tag è richiesto
          # (opzionale) use-cache: 'true'


      - name: Write kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 -d > kubeconfig
          echo "KUBECONFIG=$PWD/kubeconfig" >> $GITHUB_ENV

      # se devi solo applicare manifest già presenti nel repo:
      - name: Apply manifests
        run: |
          kubectl --kubeconfig "$KUBECONFIG" -n app apply -f k8s/
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push image
        run: |
          IMAGE=ghcr.io/${{ github.repository }}/app:${{ github.sha }}
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          docker build -t "$IMAGE" .
          docker push "$IMAGE"

      - name: Set image on Deployment
        run: |
          kubectl --kubeconfig "$KUBECONFIG" -n app set image deploy/app app=${{ env.IMAGE }} || true
